from typing import Any

class OptimalDecisionTreeClassifier:
    def __init__(
        self,
        strategy: str = ..., 
        timeout: int | None = ..., 
        lowerbound: str = ..., 
        upperbound: str = ..., 
        cart_upperbound: str = ..., 
        intermediates: bool = ..., 
        memory_limit: int | None = ..., 
    ) -> None: ...

    def fit(self, X: Any, y: Any) -> None: ...
    def predict(self, X: Any) -> Any: ...
    def tree(self) -> Any: ...
    def status(self) -> str: ...
    def is_perfect(self) -> bool: ...
    def branch_count(self) -> int: ...
    def tree_size(self) -> int: ...
    def intermediate_lbs(self) -> Any: ...
    def intermediate_ubs(self) -> Any: ...
    def expansions(self) -> int: ...
    def memory_usage_bytes(self) -> int: ...


def all_search_strategies() -> list[str]: ...
def all_lowerbounds() -> list[str]: ...
def all_upperbounds() -> list[str]: ...
def all_cart_upperbounds() -> list[str]: ...